server.servlet.context-path=/lms
server.port=8080

spring.thymeleaf.cache=false

server.servlet.session.timeout=100m

spring.messages.basename=messages,errors,setting

mybatis.config-location=classpath:/mybatis-config.xml

setting.lock.count=3
setting.lock.minute=1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tisdb
spring.datasource.username=tisuser
spring.datasource.password=systemsss

logging.config=classpath:log4j2.xml

spring.mail.host=smtp.3sss.co.jp
spring.mail.port=587
spring.mail.username=experience_java@3sss.co.jp
spring.mail.password=T6MW3CQY
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
mail.sender.name=LMS\u5b66\u7fd2\u7ba1\u7406\u30b7\u30b9\u30c6\u30e0
mail.cc=
#\u4e00\u5b9a\u671f\u9593\u3092\u904e\u304e\u305f\u53d7\u8b1b\u751f\u691c\u7d22\u306e\u671f\u9593\u6307\u5b9a
setting.search.pastTime=6
setting.search.pastTimeLabel=6\u30f5\u6708

logging.level.org.mybatis=DEBUG
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.resultsettable=DEBUG
logging.level.org.springframework.jdbc=DEBUG
